# Generated by Django 4.1.5 on 2023-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_order_product_orderitem_order_products_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
