# Generated by Django 4.1.5 on 2023-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(null=True),
        ),
    ]
